### ISSUE TITLE
We don't know what to do

### ISSUE THREAD

**Issue by munchkineatter** [gitec-webteam/gitec-webteam.github.io#18]
Connor we haven't got any clue how to help create this website..

**Comment by arcangle180** [comment]
basically, haml compiles to html, scss compiles to css, and coffee script compiles to javascript. All of the compiling is done through the program <a href="https://prepros.io/"> prepros</a> this way everything is separated. For right now, look at the site, if something is wrong or needs added/removed, create and issue, branch the repo, fix the issue, create a pull request, merge the branch back into the master. Right now we mainly need design stuff, so textures, color schemes, images, banners, etc. Stuff like that would be really helpful right now. any images and stuff go ahead and put them into the resources folder.
